"""QueryTrace — the minimal per-query record persisted to SQLite.

One row per chat/query turn. There is deliberately no traces API or UI in
ragline; the table exists so usage and quality can be analysed later with
plain SQL (e.g. token spend per session, confidence over time).
"""

from datetime import datetime

from sqlmodel import Field, SQLModel


class QueryTrace(SQLModel, table=True):
    """Persistent record of one answered query."""

    # UUID string generated by TraceCollector at query start.
    id: str = Field(primary_key=True)
    # When the query finished (UTC).
    created_at: datetime
    # The user's question exactly as asked.
    query: str
    # Chat session this turn belonged to ("" for one-shot /query calls).
    session_id: str = ""
    # Whole-turn token totals accumulated across EVERY LLM call in the turn
    # (pre-pass + answer + memory post-pass + confidence) — the "simple
    # overall token usage score" the product exposes.
    prompt_tokens: int = 0
    completion_tokens: int = 0
    # End-to-end wall time for the turn, in milliseconds.
    total_ms: float = 0.0
    # How many distinct citations the answer carried.
    citation_count: int = 0
    # Confidence score from the post-answer scorer (None when disabled).
    confidence_score: float | None = None
    # Per-stage wall time as a JSON object {stage: milliseconds} — where
    # total_ms went (embed, search, rerank, graph, answer, ...). Stages are
    # those wrapped in tracing.collector.timed_step; "{}" on older rows.
    step_ms: str = "{}"
